import {
  IconHome,
  IconFlame,
  IconCompass,
  IconBookmark,
  IconHistory,
  IconPackage,
  IconTool,
  IconBuilding,
  IconBuildingStore,
  IconBook2,
  IconRulerMeasure,
  IconMapPin,
  IconHelpCircle,
  IconMessageCircle,
  IconMoodSmile,
  IconInfoCircle,
  IconNews,
  IconSearch,
  IconMicrophone,
  IconBell,
  IconMenu2,
  IconUserCircle,
  IconHeart,
  IconPlus,
  IconMinus,
  IconChevronDown,
  IconChevronRight,
  IconChevronLeft,
  IconX,
  IconRocket,
  IconLogout,
  IconSettings,
  IconLayoutDashboard,
  IconStar,
  IconStarFilled,
  IconSend,
  IconMail,
  IconMailOpened,
  IconLock,
  IconRosette,
  IconLayoutKanban,
  IconSparkles,
  IconFileInvoice,
  IconChartHistogram,
  IconPhoto,
  IconCreditCard,
  IconStack2,
  IconPencilBolt,
  IconFlag,
  IconShare,
  IconPhone,
  IconBrandWhatsapp,
  IconCheck,
  IconArrowRight,
  IconShieldCheck,
  IconClock,
  IconTrash,
  IconPlayerPlayFilled,
  IconDownload,
  IconCalendarEvent,
  IconQuote,
  IconToolsKitchen2,
  IconBath,
  IconBed,
  IconBulb,
  IconCurrencyRupee,
  IconPlant2,
  IconStairs,
  IconDoor,
  IconBriefcase,
  IconArrowUp,
  IconArrowDown,
  type IconProps,
} from "@tabler/icons-react";
import type { FC } from "react";

/**
 * String-keyed icon registry. Content files store `icon: "home"` (plain data);
 * components render <Icon name="home" />. Add new icons to this map only.
 */
const REGISTRY = {
  home: IconHome,
  trending: IconFlame,
  explore: IconCompass,
  bookmark: IconBookmark,
  history: IconHistory,
  products: IconPackage,
  services: IconTool,
  business: IconBuilding,
  shops: IconBuildingStore,
  catalogue: IconBook2,
  architects: IconRulerMeasure,
  city: IconMapPin,
  help: IconHelpCircle,
  chat: IconMessageCircle,
  feedback: IconMoodSmile,
  about: IconInfoCircle,
  blog: IconNews,
  search: IconSearch,
  mic: IconMicrophone,
  bell: IconBell,
  menu: IconMenu2,
  user: IconUserCircle,
  heart: IconHeart,
  plus: IconPlus,
  minus: IconMinus,
  "chevron-down": IconChevronDown,
  "chevron-right": IconChevronRight,
  "chevron-left": IconChevronLeft,
  close: IconX,
  rocket: IconRocket,
  logout: IconLogout,
  settings: IconSettings,
  dashboard: IconLayoutDashboard,
  star: IconStar,
  "star-filled": IconStarFilled,
  send: IconSend,
  mail: IconMail,
  "mail-opened": IconMailOpened,
  lock: IconLock,
  rosette: IconRosette,
  kanban: IconLayoutKanban,
  sparkles: IconSparkles,
  invoice: IconFileInvoice,
  insights: IconChartHistogram,
  photo: IconPhoto,
  billing: IconCreditCard,
  plans: IconStack2,
  architecture: IconPencilBolt,
  flag: IconFlag,
  share: IconShare,
  phone: IconPhone,
  whatsapp: IconBrandWhatsapp,
  check: IconCheck,
  "arrow-right": IconArrowRight,
  verified: IconShieldCheck,
  clock: IconClock,
  trash: IconTrash,
  play: IconPlayerPlayFilled,
  download: IconDownload,
  calendar: IconCalendarEvent,
  quote: IconQuote,
  // room / category glyphs (Explore tiles, inspiration, detail specs)
  kitchen: IconToolsKitchen2,
  bath: IconBath,
  bed: IconBed,
  bulb: IconBulb,
  rupee: IconCurrencyRupee,
  plant: IconPlant2,
  stairs: IconStairs,
  door: IconDoor,
  briefcase: IconBriefcase,
  // leaderboard / KPI direction
  "arrow-up": IconArrowUp,
  "arrow-down": IconArrowDown,
} satisfies Record<string, FC<IconProps>>;

export type IconName = keyof typeof REGISTRY;

export interface IconProps_ extends IconProps {
  name: IconName;
}

export function Icon({ name, size = 20, stroke = 1.8, ...rest }: IconProps_) {
  const Cmp = REGISTRY[name];
  return <Cmp size={size} stroke={stroke} {...rest} />;
}
