import type { ReelItem } from "@/types/marketplace";

/**
 * Featured shorts — ported 1:1 from the prototype (assets/ib-shorts-data.js).
 * Real YouTube ids drive both the thumbnail and the modal embed.
 */
export const SHORTS: ReelItem[] = [
  {
    id: "sh-001",
    title: "Walnut modular kitchen, installed in 21 days",
    studio: "Verma Studio",
    city: "Saket, Delhi",
    kind: "Service",
    icon: "services",
    bg: "linear-gradient(135deg,#085041,#1d9e75)",
    youtubeId: "aqz-KE-bpKQ",
    rank: 1,
    rating: 4.8,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
  },
  {
    id: "sh-002",
    title: "Frameless glass shower enclosure — 10mm toughened",
    studio: "AquaLine Sanitary",
    city: "Dwarka, Delhi",
    kind: "Product",
    icon: "products",
    bg: "linear-gradient(135deg,#854f0b,#d4823a)",
    youtubeId: "eRsGyueVLvQ",
    rank: 2,
    rating: 4.6,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=eRsGyueVLvQ",
  },
  {
    id: "sh-003",
    title: "Inside a 3BHK turnkey interior in Gurugram",
    studio: "Hashmi Infrabuild",
    city: "Gurugram",
    kind: "Business",
    icon: "business",
    bg: "linear-gradient(135deg,#04342c,#1d9e75)",
    youtubeId: "R6MlUcmOul8",
    rank: 3,
    rating: 4.9,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=R6MlUcmOul8",
  },
  {
    id: "sh-004",
    title: "Smart-blind reveal — app + voice controlled",
    studio: "HighTech Windows Blind",
    city: "Noida",
    kind: "Product",
    icon: "products",
    bg: "linear-gradient(135deg,#185fa5,#5a9bd9)",
    youtubeId: "TLkA0RELQ1g",
    rank: 4,
    rating: 4.7,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=TLkA0RELQ1g",
  },
  {
    id: "sh-005",
    title: "Full bathroom remodel — before & after",
    studio: "Perfekte Küchen",
    city: "Rohini, Delhi",
    kind: "Service",
    icon: "services",
    bg: "linear-gradient(135deg,#5a1a7a,#9b54c4)",
    youtubeId: "Y-rmzh0PI3c",
    rank: 5,
    rating: 4.5,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=Y-rmzh0PI3c",
  },
  {
    id: "sh-006",
    title: "Boutique café interior — concept to handover",
    studio: "Studio Anteroom",
    city: "Hauz Khas, Delhi",
    kind: "Business",
    icon: "business",
    bg: "linear-gradient(135deg,#72243e,#b84d73)",
    youtubeId: "WhWc3b3KhnY",
    rank: 6,
    rating: 4.8,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=WhWc3b3KhnY",
  },
  {
    id: "sh-007",
    title: "Italian quartz countertop — slab to install",
    studio: "StoneCraft Surfaces",
    city: "Faridabad",
    kind: "Product",
    icon: "products",
    bg: "linear-gradient(135deg,#854f0b,#d4823a)",
    youtubeId: "Gv8j4tWGZdQ",
    rank: 7,
    rating: 4.6,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=Gv8j4tWGZdQ",
  },
  {
    id: "sh-008",
    title: "Wardrobe build — floor-to-ceiling in one day",
    studio: "Verma Studio",
    city: "Saket, Delhi",
    kind: "Service",
    icon: "services",
    bg: "linear-gradient(135deg,#085041,#1d9e75)",
    youtubeId: "mN0zPOpADL4",
    rank: 8,
    rating: 4.8,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=mN0zPOpADL4",
  },
  {
    id: "sh-009",
    title: "Office fit-out — 40 seats, two weeks",
    studio: "Hashmi Infrabuild",
    city: "Gurugram",
    kind: "Business",
    icon: "business",
    bg: "linear-gradient(135deg,#04342c,#1d9e75)",
    youtubeId: "jNQXAC9IVRw",
    rank: 9,
    rating: 4.9,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=jNQXAC9IVRw",
  },
  {
    id: "sh-010",
    title: "Matte-black sanitaryware collection",
    studio: "AquaLine Sanitary",
    city: "Dwarka, Delhi",
    kind: "Product",
    icon: "products",
    bg: "linear-gradient(135deg,#333,#777)",
    youtubeId: "aqz-KE-bpKQ",
    rank: 10,
    rating: 4.6,
    platform: "youtube",
    url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
  },
];
